trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: '1.6.6'

stages:
- stage: Terraform
  jobs:
  - job: DeployRG
    steps:

    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(TF_VERSION)

    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'AzureServiceConnection'
        backendAzureRmResourceGroupName: 'tfstate-rg'
        backendAzureRmStorageAccountName: 'tfstateuvstore'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'rg.tfstate'

    - task: TerraformTaskV4@4
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'AzureServiceConnection'

    - task: TerraformTaskV4@4
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'AzureServiceConnection'
        args: '-auto-approve'
